name: CMake MacOS

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-10.15, macos-11 ]
        compiler:
          - version: 12
            cc: "clang"
            cxx: "clang++"
          - version: 13
            cc: "$(brew --prefix llvm)/bin/clang"
            cxx: "$(brew --prefix llvm)/bin/clang++"

    name: ${{ matrix.platform }} - Clang ${{ matrix.compiler.version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Dependencies
        run: |
          brew install bison flex
          echo "$(brew --prefix bison)/bin" >> $GITHUB_PATH
          echo "$(brew --prefix flex)/bin" >> $GITHUB_PATH

      - name: Configure CMake
        run: |
          export CC=${{ matrix.compiler.cc }}
          export CXX=${{ matrix.compiler.cxx }}
          cmake -B ${{ github.workspace }}/build -D CMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ github.workspace }}/build/test
        run: ctest -C ${{ env.BUILD_TYPE }} --rerun-failed --output-on-failure
