name: Code Coverage with Codecov

on: [ push, pull_request ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autopoint lcov

      - name: Build Dependencies
        run: |
          wget --no-check-certificate http://ftp.gnu.org/gnu/bison/bison-3.7.4.tar.gz
          tar -xf bison-3.7.4.tar.gz
          cd bison-3.7.4
          ./configure
          sudo make -j 4 install

      - name: Configure CMake with Coverage
        run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_CXX_FLAGS=--coverage

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: lcov
        working-directory: ${{github.workspace}}/build
        run: |
          lcov -d core --capture --output-file coverage.info
          lcov --list coverage.info

      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          working-directory: ${{github.workspace}}/build
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: coverage.info
